<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetVersion)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Puhu.Btop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\lib\puhu\src\Puhu.Plugin\Puhu.Plugin.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Puhu.Btop.Tests" />
  </ItemGroup>
</Project>
