name: Build & Test

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "*.md"
      - ".github/workflows/release.yml"
      - ".github/workflows/commitlint.yml"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GLOBAL_JSON_PATH: "./src/global.json"
  SOLUTION_PATH: "./src/Puhu.Btop.slnx"

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: ${{ env.GLOBAL_JSON_PATH }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} -c Release --no-restore

      - name: Test
        working-directory: ./src
        run: dotnet test --solution Puhu.Btop.slnx -c Release --no-build
